.\" This Source Code Form is subject to the terms of the Mozilla Public
.\" License, v. 2.0. If a copy of the MPL was not distributed with this
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/.
.\"
.\" Copyright (c) 2016 David Jackson
.Dd July 10, 2016
.Dt CYMKD 3
.Os
.Sh NAME
.Nm cymkd_render cymkd_render_file
.Sh LIBRARY
.Lb libctache
.Sh SYNOPSIS
.In cymkd.h
.Ft void
.Fo cymkd_render
.Fa "const char *str" "size_t str_len" "FILE *out_fp"
.Fc
.Ft void
.Fo cymkd_render_file
.Fa "FILE *in_fp" "FILE *out_fp"
.Fc
.Sh DESCRIPTION
The cymkd_render function is used to render a string that contains markdown
markup data to an HTML file. Similarly, the cymkd_render_file function is used
to render a file directly from a FILE pointer. Internally it will read the
file into a string and render the string.
.Sh SEE ALSO
.Xr cymkd 1
