.\" This Source Code Form is subject to the terms of the Mozilla Public
.\" License, v. 2.0. If a copy of the MPL was not distributed with this
.\" file, You can obtain one at http://mozilla.org/MPL/2.0/.
.\"
.\" Copyright (c) 2016-2018 David Jackson
.Dd July 5, 2016
.Dt CYTO 1
.Os
.Sh NAME
.Nm cyto
.Nd simple static site generator
.Sh SYNOPSIS
.Nm
.Op Ar command
.Sh DESCRIPTION
Generate static websites from a collection of template files.
.Ss FLAGS
The following are flags that can be set:
.Bl -tag -width Ds
.It Fl h
print help message
.It Fl V
print version number
.It Fl j Ar num_worker_threads
Set the number of worker threads.
These threads are used to process the files
in parallel.
.El
.Ss COMMANDS
The available
commands are:
.Bl -tag -width Ds
.It cyto init Ar project
Create a directory named for
.Ar project
and initialize a Cytogen project within it.
.It cyto generate
Within a cytogen project directory, generate the static site to a directory
called _site.
.It cyto clean
Clean up the generated site, i.e. remove the _site directory
.It cyto serve
Within a cytogen-generated-site tree (i.e. the _site directory), serve the site
with a local HTTP server.
.El
.Sh SEE ALSO
.Xr ctache 1
.Xr cytogen 1
